---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wif-dashboard-crt
spec:
  secretName: wif-dashboard-crt-secret
  dnsNames:
    - wif-dashboard.incubateur.social.gouv.fr
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - wif-dashboard.incubateur.social.gouv.fr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
